language: python
os:
  - linux
  - osx
  - windows
python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install -U requests
script: pytest # run tests