language: python
os: linux
arch:
  - amd64
  - ppc64le
  - s390x
  - arm64
python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7
jobs:
  include:
    # ======= OSX ========
#     ----- changes in Travis images means this doesn't work for versions before 3.7.5 ---
    - name: "Python 3.7.5 on macOS 10.14"
      os: osx
      arch:
        - amd64
        - ppc64le
        - s390x
        - arm64
      osx_image: xcode11.2  # Python 3.7.5 running on macOS 10.14.3
      language: shell       # 'language: python' is an error on Travis CI macOS
      before_install:
        - python3 --version
        - pip3 install -U pip
        - pip3 install -U pytest
        - pip3 install -U requests
      script: python3 -m pytest
    #  ====== WINDOWS =========
    - name: "Python 2.7 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      arch:
        - amd64
        - ppc64le
        - s390x
        - arm64
      language: shell # 'language: python' errors Travis CI Windows
      before_install:
        - choco install python2
        - python --version
        - python -m pip install --upgrade pip
        - pip install --upgrade pytest
        - pip install --upgrade requests
      env: PATH=/c/Python27:/c/Python27/Scripts:$PATH
    - name: "Python 3.5.4 on Windows"
      arch:
        - amd64
        - ppc64le
        - s390x
        - arm64
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.5.4
        - python --version
        - python -m pip install --upgrade pip
        - pip3 install --upgrade pytest
        - pip3 install --upgrade requests
      env: PATH=/c/Python35:/c/Python35/Scripts:$PATH
    - name: "Python 3.6.8 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      arch:
        - amd64
        - ppc64le
        - s390x
        - arm64
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.6.8
        - python -m pip install --upgrade pip
        - pip3 install --upgrade pytest
        - pip3 install --upgrade requests
      env: PATH=/c/Python36:/c/Python36/Scripts:$PATH
    - name: "Python 3.7.4 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      arch:
        - amd64
        - ppc64le
        - s390x
        - arm64
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.7.4
        - python -m pip install --upgrade pip
        - pip3 install --upgrade pytest
        - pip3 install --upgrade requests
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH

install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install -U requests
script: pytest # run tests